name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  version_check:
    runs-on: ubuntu-latest
    outputs:
      should_update: ${{ steps.set_output.outputs.should_update }}
    steps:
        - uses: actions/checkout@v2
    
        - name: Get Commit version
          run: |
            VER=$(cat version.txt)
            echo "VERSION=$VER" >> $GITHUB_ENV
            
        - name: Get latest release
          id: latest_release
          uses: pozetroninc/github-action-get-latest-release@master
          with:
            repository: ${{ github.repository }}
            token: ${{ secrets.GITHUB_TOKEN }}

        - id: set_output
          run: |
            echo "Repo: ${{ github.repository }}"
            echo "Release info: ${{ steps.latest_release }}"
            echo "Comparing latest release (${{ steps.latest_release.release }}) and repo version (${{ env.VERSION }})."
            verlte() {
                [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
            }
            verlt() {
                [ "$1" = "$2" ] && return 1 || verlte $1 $2
            }
            if $(verlt ${{ steps.latest_release.release }} ${{ env.VERSION }}); then
              echo "Latest release is not older than repo version; no update needed."
              echo "should_update=false" >> "$GITHUB_OUTPUT"
            else
              echo "Latest release is older than repo version; needs updating."
              echo "should_update=true" >> "$GITHUB_OUTPUT"
            fi
          
        
  build:

    runs-on: ubuntu-latest
    needs: [version_check]
    if: needs.version_check.outputs.should_update == 'true'
    steps:
    - uses: actions/checkout@v2

    - name: Get version
      run: |
        VER=$(cat version.txt)
        echo "VERSION=$VER" >> $GITHUB_ENV

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: build.spec
    
    - name: Move EXE
      run: |
        mv dist/windows/WacK-Repackager.exe dist/WacK-Repackager.exe
        rm -rf dist/windows

    - name: Rename folder
      run: |
        DIR_NAME=WacK-Repackager-${{ env.VERSION }}_windows-x64
        mv dist $DIR_NAME
        echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: ${{ env.DIR_NAME }}
